#Coremod SortingIndex override: SortingIndex.<coremod class>=<number> sets a coremod's load order.
#Example: SortingIndex.com.mitchej123.hodgepodge.core.HodgepodgeCore=1
#Fri Jun 19 13:30:03 BRT 2026
enableSortingIndexOverrides=true
