#Coremod SortingIndex override: SortingIndex.<coremod class>=<number> sets a coremod's load order.
#Example: SortingIndex.com.mitchej123.hodgepodge.core.HodgepodgeCore=1
#Mon Jun 22 19:44:13 BRT 2026
enableSortingIndexOverrides=true
