name: Build & Test

on:
  push:
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Packwiz
        run: |
          curl -L https://github.com/packwiz/packwiz/releases/latest/download/packwiz-linux-amd64 -o packwiz
          chmod +x packwiz

      - name: Refresh index
        run: ./packwiz refresh

      - name: Export Modrinth pack
        run: ./packwiz modrinth export

      - name: Export CurseForge pack
        run: ./packwiz curseforge export

      - name: Rename outputs
        run: |
          mv *.mrpack AngolanosFantasy.mrpack
          mv *.zip AngolanosFantasy.zip

      - uses: actions/upload-artifact@v4
        with:
          name: modpack-build
          path: |
            AngolanosFantasy.zip
            AngolanosFantasy.mrpack